name: pelican
dependencies:
    - python=3.7.3
    - ipykernel==5.1.1
    - ipython==7.5.0
    - nbconvert==5.5.0
    - markdown==3.1.1
    - pip
    - pip:
        - pelican==4.0.1
        - pymdown-extensions=6.0
