name: pelican
dependencies:
  - python
  - ipykernel
  - ipython
  - jupyter
  - 'nbconvert>=5,<6'
  - markdown
  - pip
  - pip:
      - pelican
      - pymdown-extensions
      - pelican-jupyter
  - python=3.7
