name: build blog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Get Pelical Themes
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/../pelican-themes"
          pushd "${GITHUB_WORKSPACE}/../pelican-themes"
          git clone https://github.com/napsternxg/pelican-bootswatch.git
          ls -ltrh ${GITHUB_WORKSPACE}
          ls -ltrh ${GITHUB_WORKSPACE}/..
          ls -ltrh ${GITHUB_WORKSPACE}/../..
          popd
      
      - name: Fetch blog repo
        uses: actions/checkout@v2
        with:
            submodules: 'true'
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pelican
          environment-file: 'environment.yml'
          python-version: 3.7
          auto-activate-base: false
      
      - name: Setup software
        run: |
          sudo apt-get -y install make

      - name: Generate blog
        run: |
          cd "${GITHUB_WORKSPACE}"
          DEBUG=1 make publish

      - name: Push blog
        run: |
          cd "${GITHUB_WORKSPACE}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated Blog using $GITHUB_SHA"
          git push

