name: build blog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Pelical Themes
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/../pelican-themes"
          pushd "${GITHUB_WORKSPACE}/../pelican-themes"
          git clone https://github.com/napsternxg/pelican-bootswatch.git
          ls -ltrh ${GITHUB_WORKSPACE}
          ls -ltrh ${GITHUB_WORKSPACE}/..
          ls -ltrh ${GITHUB_WORKSPACE}/../..
          popd
      
      - name: Fetch blog repo
        uses: actions/checkout@v2          
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pelican
          environment-file: 'environment.yml'
          python-version: 3.8
          auto-activate-base: false
      
      - name: Setup software
        run: |
          sudo apt-get -y install make

      - name: Generate blog
        run: |
          cd "${GITHUB_WORKSPACE}"
          make production

      - name: Push blog
        run: |
          cd "${GITHUB_WORKSPACE}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated Blog using $GITHUB_SHA"
          git push
          
        
      
      
          
        
